spring:
  cloud:
    gateway:
      routes:
        # auth api 라우팅
        - id: auth-api-route
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**
        # 로그아웃 라우팅
        - id: auth-logout-route
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/logout
            - Method= POST
          filters:
            - JwtAuthenticationFilter
        # account api 라우팅
        - id: account-api-route
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/api/account/**
        # monitoring api 라우팅
        - id: monitoring-route
          uri: lb://MONITORING-SERVICE
          predicates:
            - Path=/api/monitor/**
          filters:
            - JwtAuthenticationFilter