spring:
  profiles:
    active: @spring.profiles.active@
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/login

server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://192.168.0.23:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: info, health
