name: Java CI/CD with Maven

on:
  push:
    branches: ["develop", "main", "release"]
  pull_request:
    branches: ["develop", "main", "release"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Set Yaml
        uses: microsoft/variable-substitution@v1
        with:
          files: ./src/main/resources/application-prod.yml
        env:
          jwt.secret: ${{ secrets.JWT_SECRET_KEY }}

      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name : Run SonarQube
        run : mvn sonar:sonar -Dsonar.projectKey=github-action -Dsonar.host.url=${{secrets.SONAR_HOST}} -Dsonar.login=${{secrets.SONAR_TOKEN}}
      #Deploy
      - name: Docker build & push
        run: |
          docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"
          docker build -t "${{ secrets.DOCKER_USERNAME }}"/api-gateway .
          docker push "${{ secrets.DOCKER_USERNAME }}"/api-gateway

      - name: SSH to Server and Docker pull & up
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_ID }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker pull "${{ secrets.DOCKER_USERNAME }}"/api-gateway
            docker stop api-gateway || true
            docker rm api-gateway || true 
            docker run -d --network t1bridge --name api-gateway "${{ secrets.DOCKER_USERNAME }}"/api-gateway

